variables:
  SANITY_MODE: ""

hello world:
    stage: build
    script:
        - env
        - echo $SANITY_MODE

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

get env info:
    image: alpine:edge
    script: 
        - env | tee -a howdy.txt
    artifacts:
        paths:
            - howdy.txt

secret_detection:
  artifacts:
      paths:
          - gl-secret-detection-report.json
